update join_radar to also append instrument parameters
ARM-DOE/pyart pull request #1204
Opened 2022-07-15 15:46 UTC by wolfidan

Hi dear Py-ART team,

The join_radar function in Py-ART has the problem that it does not merge instrument parameters. This is an issue for certain functions for example _dealias_region_based_, which expects a nyquist_velocity value for every sweep. I think there is currently no way to use this function on a multi sweep scan obtained with join_radar. In our MeteoSwiss version we use the function in this PR, which also merges the most important instrument parameters and is able to merge radar objects which have different variables (by merging only the variables that they have in common).
The code below for example fails for me with the current Py-ART version with error

_nyquist_vel = [radar.get_nyquist_vel(i, check_uniform) for i in 
return(nyq_vel[0])
TypeError: only size-1 arrays can be converted to Python scalars_

 but works with this fix.  
````

for i,f in enumerate(files):
    radar =  pyart.io.read_cfradial(f)
    if i == 0:
        mradar = radar
    else:
        mradar = pyart.util.join_radar(mradar, radar)
    
    
wind = pyart.correct.dealias_region_based(mradar, ref_vel_field = 'velocity')

````
Cheers,
Damoeé

2022-07-15 16:11 UTC, wolfidan commented
Sorry warn function is missing, I'll fix that ASAP.

2022-07-15 16:11 UTC, zssherman commented
Thanks @wolfidan for doing this! Yeah once the warn is fix illl do another review.

2022-07-15 16:51 UTC, zssherman commented
@wolfidan Looks good, only thing is there is an added whitespace near the top making 3 spaces between the two functions. More nitpicking, but besides that everything looks good.

2022-07-18 14:19 UTC, mgrover1 requested changes
@wolfidan thanks for adding this fix! One small suggestion - could you please add a test for this?

2022-07-18 23:01 UTC, zssherman commented
Doing a test on CI, why there was a close and reopen

2022-07-19 08:09 UTC, wolfidan commented
Thank you @mgrover1, I have added an unittest that check if a join of two radars with different numbers of sweeps and only one common field is possible.

2022-07-19 15:25 UTC, mgrover1 approved these changes
Great! Thanks @wolfidan

2022-07-19 16:32 UTC, merged