ADD: addition of cut_radar function in radar_utils
ARM-DOE/pyart pull request #1227
Opened 2022-07-27 19:46 UTC by wolfidan

Dear Py-ART team,

In this PR I propose the addition of a cut_radar function from our MeteoSwiss fork of the library (thanks @jfigui). It cuts a radar object to a new domain specified by bounds in range, azimuth and elevation, and returns a new object. It can be useful to make processing faster when one is interested only in a certain subdomain around the radar (typically shorter ranges and only a certain sector).
This function is used a lot in our [pyrad](https://github.com/MeteoSwiss/pyrad) library, which is  a framework for real time radar processing that relies on PyART. 
I also added a short test function that checks if a cut radar object has indeed coordinates that match with the specified bounds.
Cheers,
Daniel W.

2022-07-27 19:50 UTC, mgrover1 requested changes
One small suggestion - other than that, looks great! Thanks for adding tests!

2022-07-27 19:50 UTC, mgrover1 commented on pyart/util/radar_utils.py
> +def cut_radar(radar, field_names, rng_min=None, rng_max=None, ele_min=None,
This all looks great! One small suggestion - what would you think about changing the name here to subset_radar?

2022-07-28 08:34 UTC, wolfidan commented
Thanks for the feedback @mgrover1, it's done

2022-07-28 09:47 UTC, wolfidan commented
Could you help me with this failing check, I have honestly no idea what failed here in the website deploy?

2022-07-28 12:02 UTC, mgrover1 commented
@wolfidan we updated the trmm_rsl feedstock, changing the path in our CI. I added the fix here, should fix the problem. Thanks for making those changes!

2022-07-28 12:44 UTC, mgrover1 approved these changes

2022-07-28 13:29 UTC, zssherman commented
@mgrover1 looks like it's still not finding trmm_rsl, the full path on condaforge has a weird extension now before the 4 and after the package name

2022-07-28 13:30 UTC, zssherman commented
And it's different between osx and Linux for some reason... hmmm

2022-07-28 15:07 UTC, mgrover1 commented
I updated the TRMM rsl path - it was incorrect...

2022-07-28 18:16 UTC, wolfidan commented
Thanks for your help!

2022-08-11 18:34 UTC, mgrover1 commented
@zssherman I think we can go ahead and merge - let's fix the TRMM_RSL for linux in a different PR

2022-08-12 21:54 UTC, merged