ADD: Colorbar Manipulation Example
ARM-DOE/pyart pull request #1300
Opened 2022-10-23 23:56 UTC by jrobrien91

Example to manipulate the title and size of a colorbar object

2022-10-25 12:37 UTC, mgrover1 commented on examples/plotting/plot_modify_colorbar.py
> +cbar = plt.colorbar(mappable=display.plots[0], fraction=0.04, ax=axsB)
Should you be able to set cbar = display.cbs[0]? This is usually how I modify it.. display.cbs should return a list of colorbar objects

2022-10-25 20:02 UTC, zssherman requested changes

2022-10-25 20:03 UTC, zssherman commented
@jrobrien91 Figured out why it wasn't showing up, my comments were put into pending and I had to start a review to get them to appear.

2022-10-28 13:32 UTC, mgrover1 commented on examples/plotting/plot_modify_colorbar.py
> +display.plot_ppi_map('reflectivity_horizontal',
I think we should stick with the multiple lines... It makes it easier to read, and conforms to the same standards we are using ACT

2022-10-28 14:00 UTC, jrobrien91 commented
Should have some time to work on this today. Sorry for the delay!

2022-11-01 16:25 UTC, mgrover1 commented
@jrobrien91 do you need any help getting this to the finish line? Happy to help!

2022-11-16 19:24 UTC, zssherman commented on examples/plotting/plot_modify_colorbar.py
> +#display = pyart.graph.RadarMapDisplay(radar)
Can we remove the unused code?

2022-11-16 19:51 UTC, mgrover1 approved these changes
Thanks for making those changes @jrobrien91

2022-11-16 19:55 UTC, zssherman approved these changes

2022-11-16 19:56 UTC, zssherman commented on examples/plotting/plot_modify_colorbar.py
> +Modifiy a Colorbar for your Plot
Sorry last thing, modifiy to modify

2022-11-16 19:56 UTC, zssherman commented on examples/plotting/plot_modify_colorbar.py
> +Modifiy a Colorbar for your Plot
@jrobrien91 Sorry one last thing, beside that looks good!

2022-11-16 20:59 UTC, merged

2022-11-16 20:59 UTC, zssherman commented
Thanks @jrobrien91 merging.