ENH: Column Vertical Profile (CVP) Addition
ARM-DOE/pyart pull request #1478
Opened 2023-10-24 18:33 UTC by jrobrien91

Based on Murphy et al. (2020) and Bukovčić et al. (2020), a function to retrieve a columnar vertical profile (CVP) was added to the columnsect.py utility. 

Instead of extracting single gates from a single azimuth above a location (e.g. `get_field_location`), `column_vertical_profile` allows the user to define the number of azimuths and range gates to include with in this extraction. 

While providing similar functionality as `get_field_location`, `column_vertical_profile` adds more samples to the extracted column, increasing frequency of valid data at lower elevation gates. This ultimately allows for easier comparison with in-situ observations. 

- [X] Tests added
- [X] Documentation reflects changes

2023-10-24 18:35 UTC, zssherman commented
@jrobrien91 Thanks for the PR, I'll review here in a moment!

2023-10-24 19:06 UTC, zssherman requested changes
@jrobrien91 Mostly docstring fixes etc. The code itself looks good. The new unit test looks to be failing

2023-10-24 19:06 UTC, zssherman commented on pyart/util/columnsect.py
> +        Xarary Dataset containing the radar column above the target for
Xarary to Xarray

2023-10-24 19:06 UTC, zssherman commented on pyart/util/columnsect.py
> +
Can remove spacing between parameter list

2023-10-24 19:06 UTC, zssherman commented on pyart/util/columnsect.py
> +
Same here

2023-10-24 19:06 UTC, zssherman commented on pyart/util/columnsect.py
> +
Remove space

2023-10-24 19:06 UTC, zssherman commented on pyart/util/columnsect.py
> +    Radar Sweep from which fields are extracted from the target locations
Indent by 4 spaces

2023-10-24 19:06 UTC, zssherman commented on pyart/util/columnsect.py
> +    List containing indices for the gates of interest
Same here, indent

2023-10-24 19:06 UTC, zssherman commented on pyart/util/columnsect.py
> +    dictionary containing averaged subset fields for target location
Indent here as well

2023-10-24 19:06 UTC, zssherman commented on pyart/util/columnsect.py
> +
Remove space

2023-10-24 19:06 UTC, zssherman commented on pyart/util/columnsect.py
> +
Remove space

2023-10-24 19:06 UTC, zssherman commented on pyart/util/columnsect.py
> +
More below

2023-10-24 20:40 UTC, jrobrien91 commented
@zssherman thanks for catching all those! I've resubmitted the changes

2023-10-24 21:13 UTC, zssherman approved these changes

2023-10-24 21:13 UTC, zssherman commented
@jrobrien91 I did a few more changes, not sure why the doc build is failing though..

2023-10-24 21:23 UTC, jrobrien91 commented
@zssherman thanks for catching those doc-string issues! Not sure why the docs are failing either. 

looks like xradar issue?

2023-10-24 21:39 UTC, zssherman commented
@jrobrien91 Yeah we might need to wait on @mgrover1 , I can dig into the code in the meantime

2023-10-24 21:40 UTC, zssherman commented
@jrobrien91 Actually looks more like a pathlib issue, i'll check their forums

2023-10-24 21:51 UTC, zssherman commented
Pinning 3.11 for doc build for now.

2023-10-30 16:57 UTC, mgrover1 approved these changes
This looks great! Nice work @jrobrien91

2023-10-30 17:41 UTC, mgrover1 commented on doc/environment.yml
> +  - python=3.11
```suggestion
```

2023-10-30 17:42 UTC, mgrover1 commented on doc/environment.yml
> +  - python=3.11
We do not need this anymore now that we have a release of datatree with the fix.

2023-10-30 17:51 UTC, zssherman approved these changes

2023-10-30 20:47 UTC, mgrover1 approved these changes

2023-10-30 20:48 UTC, mgrover1 commented
The CI/linting issues have been resolved! Good to merge!

2023-10-30 20:51 UTC, merged