ADD: function to create CFADs
ARM-DOE/pyart pull request #1492
Opened 2023-12-05 22:09 UTC by lauratomkins

Hi folks,

I have another PR which adds functionality to create CFADs with radar data. I've included an example as well. Not sure if my functions are in the right place so please let me know if you have any feedback!

Thanks!

2023-12-05 23:49 UTC, zssherman commented
@lauratomkins Thanks for the PR! I will take a look shortly, Max will likely as well soon.

2023-12-06 14:30 UTC, mgrover1 requested changes
This looks fantastic! My only suggestion here would be to pass in radar object as input for the cfad function, similar to the composite reflectivity function https://github.com/ARM-DOE/pyart/blob/main/pyart/retrieve/comp_z.py#L16

Then have a `field="reflectivity"` argument by default; this will make it easier for users to plug in their radar data, as well as being consistent with submodules.

2023-12-11 16:05 UTC, lauratomkins commented
@mgrover1 thanks for the suggestion. Ideally, I'd like this function to work with both radar and grid objects. I started writing the function in a way that would accept both, but I'm wondering if it makes more sense to have two functions, one for radar objects and one for grid objects? Do you have any other functions that can work on both types of objects that I can use as a reference? Or do you have any suggestions on the best way to handle this?

2023-12-18 19:22 UTC, zssherman commented
@lauratomkins Max is currently out at a deployment, why it's been slightly quiet with this PR. I'm wondering too, if we can just have a pyart object, without having to have one for the grid and one for a radar object. The field data is accessed I believe the same if we called radar.fields['reflectivity']['data'] and grid.fields['reflectivity']['data'] so might be able to make it still universal if we are going the route Max suggested while still maintaining one function. We can see what else Max thinks once he returns.

2024-01-02 14:28 UTC, mgrover1 commented
I agree with @zssherman here; as long as the object is able to access `radar.fields[reflectivity_field]`  it should be good.

2024-01-23 21:02 UTC, lauratomkins commented
Apologies for the delay but I think I've updated it in a way that makes sense. Please let me know if it needs any more changes. Also, I'm not sure how to discard a commit, but I believe that my changes to the `plot_feature_detection.py` file is causing merging issues. I believe the issue that I was trying to correct was fixed so it can be discarded.

2024-01-23 21:51 UTC, zssherman approved these changes

2024-01-25 19:50 UTC, zssherman commented on pyart/retrieve/cfad.py
> +        except:
We might want to do a full error catching here like a ValueError or something similiar. @mgrover1 thoughts?

2024-01-25 19:51 UTC, zssherman commented on pyart/retrieve/cfad.py
> +        altitude row are masked.
Space line between the headers of each section, Returns, references etc I think is needed for sphinx to generate correctly.

2024-01-25 19:52 UTC, zssherman commented
@lauratomkins I added just to more comments, besides that I think this is almost good to go! I'll let @mgrover1 do a final review on my suggestions and see if he has any more thoughts.

2024-01-25 19:58 UTC, mgrover1 approved these changes
This looks great! Thanks for making those changes.

2024-01-25 21:06 UTC, zssherman approved these changes

2024-01-25 22:02 UTC, merged