git logRhi cross
ARM-DOE/pyart pull request #1567
Opened 2024-04-18 21:42 UTC by isilber

- [ ] Closes #xxxx
- [ ] Tests added
- [ ] Documentation reflects changes

2024-04-23 14:30 UTC, mgrover1 requested changes
One minor comment - otherwise, this looks great! Thanks for your hard work here @isilber

2024-04-23 14:30 UTC, mgrover1 commented on pyart/map/grid_mapper.py
> +        NOTE: the default `min_radius` value is smaller for ARM radars
Can you specify ARM cloud radars?

2024-04-23 21:24 UTC, isilber commented on pyart/map/grid_mapper.py
> +        NOTE: the default `min_radius` value is smaller for ARM radars
Done. Thanks, @mgrover1

2024-04-24 01:50 UTC, zssherman approved these changes

2024-04-24 02:38 UTC, mgrover1 approved these changes

2024-04-30 15:57 UTC, merged