ZDR bias code from RadTraQ
ARM-DOE/pyart pull request #1630
Opened 2024-08-29 21:13 UTC by rcjackson

- [x] Addresses part of #1522 
- [x] Tests added
- [x] Documentation reflects changes

I have adapted the ZDR bias code from RadTraQ into PyART with tests and the given example.

2024-08-29 22:05 UTC, zssherman requested changes
Just some small comments, besides that, looks good!

2024-08-29 22:05 UTC, zssherman commented on pyart/correct/__init__.py
> +from .bias_and_noise import correct_bias, correct_noise_rhohv, calc_zdr_offset  # noqa
Looks like correct_noise_rhohv got duplicated in the conflict fix.

2024-08-29 22:05 UTC, zssherman commented on pyart/correct/bias_and_noise.py
> +    obj : dict
Can we rename obj to something else? Not really necessary, but more so i think obj as a class or pyart or xarray obj and not dict

2024-08-29 22:40 UTC, zssherman approved these changes

2024-08-29 22:40 UTC, zssherman commented
Doc failure is unrelated to PR, fixed in mine.

2024-08-29 22:43 UTC, zssherman commented
@rcjackson I think we got two correct_bias now, there was one on the line below of the changed one.

2024-08-30 14:28 UTC, mgrover1 approved these changes
This looks great! Thanks for the hard work here @rcjackson @zssherman

2024-08-30 14:34 UTC, merged