FIX: Minor fix in plot_maxcappi
ARM-DOE/pyart pull request #1638
Opened 2024-08-30 21:23 UTC by syedhamidali

This fix addresses an issue in the plot_maxcappi function where radar_name could appear either as a list of byte strings or a simple string.

2024-08-30 21:47 UTC, zssherman requested changes

2024-08-30 21:47 UTC, zssherman commented on pyart/graph/max_cappi.py
> +    # instrument_name = ds.attrs.get("instrument_name", "N/A")[:4]
```suggestion
```

2024-08-30 21:47 UTC, zssherman commented on pyart/graph/max_cappi.py
> +    # instrument_name = ds.attrs.get("instrument_name", "N/A")[:4]
Can we remove old code comment.

2024-08-30 21:47 UTC, zssherman commented
@syedhamidali Thanks for the PR! One comment I added

2024-08-31 03:18 UTC, syedhamidali commented on pyart/graph/max_cappi.py
> +    # instrument_name = ds.attrs.get("instrument_name", "N/A")[:4]
Sure, please go ahead.

2024-09-02 07:37 UTC, closed without merging